### ISSUE TITLE
panic!

### ISSUE THREAD

**Issue by cocap10** [containous/flaeg#21]
```
./traefik -
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
panic(0xdffac0, 0xc820010110)
	/home/martin/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
github.com/containous/traefik/vendor/github.com/containous/flaeg.argToLower(0x7fffdd35df19, 0x1, 0x0, 0x0)
	/home/martin/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:765 +0x1cb
github.com/containous/traefik/vendor/github.com/containous/flaeg.argsToLower(0xc8200a0070, 0x1, 0x1, 0x0, 0x0, 0x0)
	/home/martin/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:783 +0x109
github.com/containous/traefik/vendor/github.com/containous/flaeg.parseArgs(0xc8200a0070, 0x1, 0x1, 0xc82019f4f8, 0xc8202ebad0, 0x16, 0x0, 0x0)
	/home/martin/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:149 +0x7d2
github.com/containous/traefik/vendor/github.com/containous/flaeg.LoadWithCommand(0xc820246c80, 0xc8200a0070, 0x1, 0x1, 0xc8202eba40, 0xc820277530, 0x2, 0x2, 0x0, 0x0)
	/home/martin/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:538 +0x3c2
github.com/containous/traefik/vendor/github.com/containous/flaeg.(*Flaeg).Parse(0xc8201eacc0, 0xc820246c80, 0x1, 0x0, 0x0)
	/home/martin/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:701 +0xb8
main.main()
	/home/martin/go/src/github.com/containous/traefik/traefik.go:57 +0xd58
```

**Comment by cocap10** [comment]
Closed in PR #24
